"""empty message

Revision ID: dcc4ba80476a
Revises: ee2a0d02a7e1
Create Date: 2020-08-28 21:16:37.413513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc4ba80476a'
down_revision = 'ee2a0d02a7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.String(), nullable=False))
    op.drop_column('Show', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
